<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'RG\\TtNews\\Controller\\NewsBackendAjaxController' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Controller/NewsBackendAjaxController.php',
    'RG\\TtNews\\Database\\Database' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Database/Database.php',
    'RG\\TtNews\\Form\\FormDataProvider' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Form/FormDataProvider.php',
    'RG\\TtNews\\Helper\\Helpers' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Helper/Helpers.php',
    'RG\\TtNews\\Helper\\ItemsProcFunc' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Helper/ItemsProcFunc.php',
    'RG\\TtNews\\Hooks\\DataHandlerHook' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Hooks/DataHandlerHook.php',
    'RG\\TtNews\\Hooks\\PageModuleHook' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Hooks/PageModuleHook.php',
    'RG\\TtNews\\Menu\\Catmenu' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Menu/Catmenu.php',
    'RG\\TtNews\\Menu\\ClickMenu' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Menu/ClickMenu.php',
    'RG\\TtNews\\Middleware\\AjaxResolver' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Middleware/AjaxResolver.php',
    'RG\\TtNews\\Module\\BaseScriptClass' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/BaseScriptClass.php',
    'RG\\TtNews\\Module\\CategoryManager' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/CategoryManager.php',
    'RG\\TtNews\\Module\\LegacyBackendUtility' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/LegacyBackendUtility.php',
    'RG\\TtNews\\Module\\NewsAdminModule' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/NewsAdminModule.php',
    'RG\\TtNews\\Module\\NewsRecordlist' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/NewsRecordlist.php',
    'RG\\TtNews\\Module\\PageLayoutView' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Module/PageLayoutView.php',
    'RG\\TtNews\\Plugin\\TtNews' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Plugin/TtNews.php',
    'RG\\TtNews\\Routing\\Aspect\\ArchiveValueMapper' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Routing/Aspect/ArchiveValueMapper.php',
    'RG\\TtNews\\Tree\\Categorytree' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Tree/Categorytree.php',
    'RG\\TtNews\\Tree\\FeTreeView' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Tree/FeTreeView.php',
    'RG\\TtNews\\Tree\\TableConfiguration\\NewsDatabaseTreeDataProvider' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Tree/TableConfiguration/NewsDatabaseTreeDataProvider.php',
    'RG\\TtNews\\Update\\PopulateNewsSlugs' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Update/PopulateNewsSlugs.php',
    'RG\\TtNews\\Update\\migrateCatImagesToFal' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Update/migrateCatImagesToFal.php',
    'RG\\TtNews\\Update\\migrateFileAttachmentsToFal' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Update/migrateFileAttachmentsToFal.php',
    'RG\\TtNews\\Update\\migrateImagesToFal' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Update/migrateImagesToFal.php',
    'RG\\TtNews\\Utility\\Div' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Utility/Div.php',
    'RG\\TtNews\\Utility\\IconFactory' => $typo3InstallDir . 'typo3conf/ext/tt_news/Classes/Utility/IconFactory.php',
);
